import { TocItem } from '@/types/toc';

function normalizeHeadingText(text: string): string {
    return text.replace(/\s+/g, ' ').trim();
}

export function extractHeadingsFromDom(root: ParentNode): TocItem[] {
    const headings: TocItem[] = [];
    const nodes = root.querySelectorAll('h1[id],h2[id],h3[id],h4[id],h5[id],h6[id]');

    // Track how many times each base ID has appeared so we can deduplicate
    const idCounts = new Map<string, number>();

    nodes.forEach((el) => {
        // Skip headings inside blockquotes
        if (el.closest('blockquote')) return;

        const tag = el.tagName.toLowerCase();
        const level = tag.startsWith('h') ? parseInt(tag.slice(1), 10) : NaN;
        const baseId = (el as HTMLElement).id;

        // Clone the element and strip .toc-hidden spans so duplicate headings
        // (e.g. "Response" under every endpoint) display clean text in the TOC
        // while still having unique IDs generated by DocHeading.
        const clone = el.cloneNode(true) as HTMLElement;
        clone.querySelectorAll('.toc-hidden').forEach((node) => node.remove());

        // Try to find if there's a number span (from DocHeading)
        const numberEl = clone.querySelector('.text-gray-500');
        const number = numberEl ? normalizeHeadingText(numberEl.textContent ?? '') : undefined;

        // Try to find the main text span
        const textEl = clone.querySelector('span:not(.text-gray-500)');
        const text = normalizeHeadingText((textEl ? textEl.textContent : clone.textContent) ?? '');

        if (!baseId || !text || !Number.isFinite(level)) return;
        if (level < 1 || level > 6) return;

        // Deduplicate IDs: first occurrence keeps the original, subsequent ones
        // get a suffix (-1, -2, …). Update the DOM element so anchor links work.
        const count = idCounts.get(baseId) ?? 0;
        idCounts.set(baseId, count + 1);
        const id = count === 0 ? baseId : `${baseId}-${count}`;
        if (count > 0) {
            (el as HTMLElement).id = id;
        }

        headings.push({ id, text, level, number });
    });

    return headings;
}
