// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Run 'bun run build:docs' to regenerate.

export const routeToFile: Record<string, string> = {
    '/development': 'developer-resources/index.mdx',
    '/api/overview': 'developer-resources/api/overview.mdx',
    '/get-started': 'get-started/get-started/overview.mdx',
    '/api/api-keys': 'developer-resources/api/authentication/api-keys.mdx',
    '/api/managing-api-keys': 'developer-resources/api/authentication/managing-api-keys.mdx',
    '/api/errors': 'developer-resources/api/handling-errors/errors.mdx',
    '/api/idempotency': 'developer-resources/api/make-requests/idempotency.mdx',
    '/api/request-ids': 'developer-resources/api/make-requests/request-ids.mdx',
    '/api/uris': 'developer-resources/api/make-requests/api-uris.mdx',
    '/api/account-context': 'developer-resources/api/make-requests/account-context.mdx',
    '/api/versioning': 'developer-resources/api/make-requests/versioning.mdx',
    '/api/pagination': 'developer-resources/api/make-requests/pagination.mdx',
    '/api/rate-limiting': 'developer-resources/api/make-requests/rate-limiting.mdx',
    '/api-tour': 'get-started/get-started/about-the-apis/api-tour.mdx',
    '/account/activate': 'get-started/start-building/account/activate.mdx',
    '/account/checklist': 'get-started/start-building/account/checklist.mdx',
    '/account': 'get-started/start-building/account/overview.mdx',
    '/api-request': 'get-started/start-building/start-developing/api-request.mdx',
    '/release-phases': 'get-started/start-building/start-developing/release-phases.mdx',
    '/go-live': 'get-started/start-building/start-developing/go-live.mdx',
    '/test-integration': 'get-started/start-building/start-developing/test-integration.mdx',
};

export const routeToTab: Record<string, string> = {
    '/development': 'developer-resources',
    '/api/overview': 'developer-resources',
    '/get-started': 'get-started',
    '/api/api-keys': 'developer-resources',
    '/api/managing-api-keys': 'developer-resources',
    '/api/errors': 'developer-resources',
    '/api/idempotency': 'developer-resources',
    '/api/request-ids': 'developer-resources',
    '/api/uris': 'developer-resources',
    '/api/account-context': 'developer-resources',
    '/api/versioning': 'developer-resources',
    '/api/pagination': 'developer-resources',
    '/api/rate-limiting': 'developer-resources',
    '/api-tour': 'get-started',
    '/account/activate': 'get-started',
    '/account/checklist': 'get-started',
    '/account': 'get-started',
    '/api-request': 'get-started',
    '/release-phases': 'get-started',
    '/go-live': 'get-started',
    '/test-integration': 'get-started',
};
